### PR TITLE
Focused data component

### LINKED ISSUE #65: image list incomplete
only one image loads on list of raster images even when there are multiples

### PR DESCRIPTION
**Pull request by marySalvi**
Fixes #65

### CODE REVIEW

**Review by annehaley — CHANGES_REQUESTED** [review]
I tried to view an image on result 8 (the first option in Image selected, the only option in Band selected, and opacity of 1) and I got the following error:
image

Also, is it possible to highlight the row that is currently represented in the Focused Data component?

**Review by banesullivan — CHANGES_REQUESTED** [review]
- Can you set the opacity default value to 1?
- You and I need to meet and hook this up to the Tile Layer code in the Cesium component

**Comment by banesullivan** [comment]
@annehaley, couldn't reproduce... also I'm not too worried about that error for now as we haven't hooked this up to the tile layer code yet

**Comment by annehaley** [comment]
> I'm not too worried about that error for now as we haven't hooked this up to the tile layer code yet

Okay, I hadn't realized that these parts weren't connected yet. Disregard :)

**Pull request merged**
